// Utility module defining standardized error codes for the application

// Authentication and Authorization
export const AUTH = {
    REQUIRED: "AUTH_REQUIRED",
    INVALID_TOKEN: "AUTH_INVALID_TOKEN",
    TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
    REFRESH_EXPIRED: "AUTH_REFRESH_EXPIRED",
    INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
    ACCOUNT_DISABLED: "AUTH_ACCOUNT_DISABLED",
    EMAIL_NOT_VERIFIED: "AUTH_EMAIL_NOT_VERIFIED",
};

// Validation Errors
export const VALIDATION = {
    FAILED: "VALIDATION_ERROR",
    INVALID_OBJECT_ID: "INVALID_OBJECT_ID",
    REQUIRED_FIELD: "REQUIRED_FIELD",
    INVALID_FORMAT: "INVALID_FORMAT",
    TOO_SHORT: "TOO_SHORT",
    TOO_LONG: "TOO_LONG",
};

// Resource Errors
export const RESOURCE = {
    NOT_FOUND: "RESOURCE_NOT_FOUND",
    ALREADY_EXISTS: "RESOURCE_ALREADY_EXISTS",
    FORBIDDEN: "RESOURCE_FORBIDDEN",
};

// User-related Errors
export const USER = {
    NOT_FOUND: "USER_NOT_FOUND",
    EMAIL_EXISTS: "USER_EMAIL_EXISTS",
    USERNAME_EXISTS: "USER_USERNAME_EXISTS",
    INVALID_PASSWORD: "USER_INVALID_PASSWORD",
};

// Video-related Errors
export const VIDEO = {
    NOT_FOUND: "VIDEO_NOT_FOUND",
    UPLOAD_FAILED: "VIDEO_UPLOAD_FAILED",
    PROCESSING: "VIDEO_PROCESSING",
    INVALID_FORMAT: "VIDEO_INVALID_FORMAT",
};

// Comment-related Errors
export const COMMENT = {
    NOT_FOUND: "COMMENT_NOT_FOUND",
    ALREADY_LIKED: "COMMENT_ALREADY_LIKED",
    PARENT_NOT_FOUND: "COMMENT_PARENT_NOT_FOUND",
};

// Playlist-related Errors
export const PLAYLIST = {
    NOT_FOUND: "PLAYLIST_NOT_FOUND",
    VIDEO_ALREADY_EXISTS: "PLAYLIST_VIDEO_EXISTS",
    VIDEO_NOT_FOUND: "PLAYLIST_VIDEO_NOT_FOUND",
    PRIVATE: "PLAYLIST_PRIVATE",
};

// Subscription-related Errors
export const SUBSCRIPTION = {
    SELF_SUBSCRIBE: "SUBSCRIPTION_SELF_SUBSCRIBE",
    ALREADY_SUBSCRIBED: "SUBSCRIPTION_ALREADY_EXISTS",
    NOT_SUBSCRIBED: "SUBSCRIPTION_NOT_FOUND",
};

// Rate Limiting Errors
export const RATE_LIMIT = {
    EXCEEDED: "RATE_LIMIT_EXCEEDED",
    TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
};

// Server Errors
export const SERVER = {
    INTERNAL_ERROR: "SERVER_ERROR",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
    DATABASE_ERROR: "DATABASE_ERROR",
};

export default {
    AUTH,
    VALIDATION,
    RESOURCE,
    USER,
    VIDEO,
    COMMENT,
    PLAYLIST,
    SUBSCRIPTION,
    RATE_LIMIT,
    SERVER,
};
